### ISSUE TITLE
Failed to create snapshot ... http://localhost:8585/api/v1beta1/services: Invalid argument

### ISSUE THREAD

**Issue by pimlottc** [jubeio/jube#225]
I'm following the [Getting Started](http://fabric8.io/jube/getStarted.html) guide, using jube-2.0.19-image.zip, and I get a reoccurring error approximately 15-20 minutes after startup:

```
2015-01-08 14:04:49,561 [tp1050508118-80] INFO  KubernetesService              - No GitFacade injected! Defaulting to the singleton
2015-01-08 14:05:48,000 [SessionTracker ] INFO  ZooKeeperServer                - Expiring session 0x14acb7f96560000, timeout of 60000ms exceeded
2015-01-08 14:05:48,001 [id:0 cport:-1):] INFO  PrepRequestProcessor           - Processed session termination for sessionid: 0x14acb7f96560000
2015-01-08 14:05:48,003 [ooKeeperGroup-0] INFO  Replicator                     - Replicator is the master
2015-01-08 14:20:21,758 [Timer-2        ] WARN  PhaseInterceptorChain          - Interceptor for {http://localhost:8585/}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64)[cxf-core-3.0.2.jar:3.0.2]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[cxf-core-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:619)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:674)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at com.sun.proxy.$Proxy68.getServices(Unknown Source)[:]
        at io.fabric8.kubernetes.api.KubernetesClient.getServices(KubernetesClient.java:190)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.KubernetesHelper.getServiceMap(KubernetesHelper.java:431)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView.createSnapshot(AppView.java:148)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView.refreshData(AppView.java:138)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView$1.run(AppView.java:80)[kubernetes-api-2.0.19.jar:2.0.19]
        at java.util.TimerThread.mainLoop(Timer.java:555)[:1.7.0_45]
        at java.util.TimerThread.run(Timer.java:505)[:1.7.0_45]
```

The cause looks like this:

```
WARN  ServiceResolver                - Could not invoke: getServiceUrl[kubernetes] on io.fabric8:type=KubernetesManager. javax.management.RuntimeMBeanException: javax.ws.rs.ProcessingException: java.net.SocketException: SocketException invoking http://localhost:8585/api/v1beta1/services: Invalid argument
```

Once it starts, it happens over and over again until I kill jube.

It's fully reproducible:
1. Start ./run.sh
2. Wait 20 minutes

I am trying to debug to get the contents of the CXF request but I haven't figured that out yet.

**Comment by pimlottc** [comment]
Here's a more complete stacktrace log.  You can see the startup finished and then exceptions a little more than 15 minutes later:

```
2015-01-08 18:14:27,004 [ooKeeperGroup-0] INFO  ic8.jube.replicator.Replicator - Replicator is the master
2015-01-08 18:31:43,918 [Timer-2        ] WARN  xf.phase.PhaseInterceptorChain - Interceptor for {http://localhost:8585/}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64)[cxf-core-3.0.2.jar:3.0.2]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[cxf-core-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:619)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:674)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at com.sun.proxy.$Proxy69.getReplicationControllers(Unknown Source)[:]
        at io.fabric8.kubernetes.api.KubernetesClient.getReplicationControllers(KubernetesClient.java:135)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.KubernetesHelper.getReplicationControllerMap(KubernetesHelper.java:435)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView.createSnapshot(AppView.java:149)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView.refreshData(AppView.java:138)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView$1.run(AppView.java:80)[kubernetes-api-2.0.19.jar:2.0.19]
        at java.util.TimerThread.mainLoop(Timer.java:555)[:1.7.0_45]
        at java.util.TimerThread.run(Timer.java:505)[:1.7.0_45]
2015-01-08 18:31:43,919 [Timer-2        ] WARN  .kubernetes.api.mbeans.AppView - Failed to create snapshot: javax.ws.rs.ProcessingException: java.net.SocketException: SocketException invoking http://localhost:8585/api/v1beta1/replicationControllers: Invalid argument
javax.ws.rs.ProcessingException: java.net.SocketException: SocketException invoking http://localhost:8585/api/v1beta1/replicationControllers: Invalid argument
        at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:552)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:534)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:676)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)[cxf-rt-rs-client-3.0.2.jar:3.0.2]
        at com.sun.proxy.$Proxy69.getReplicationControllers(Unknown Source)[:]
        at io.fabric8.kubernetes.api.KubernetesClient.getReplicationControllers(KubernetesClient.java:135)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.KubernetesHelper.getReplicationControllerMap(KubernetesHelper.java:435)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView.createSnapshot(AppView.java:149)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView.refreshData(AppView.java:138)[kubernetes-api-2.0.19.jar:2.0.19]
        at io.fabric8.kubernetes.api.mbeans.AppView$1.run(AppView.java:80)[kubernetes-api-2.0.19.jar:2.0.19]
        at java.util.TimerThread.mainLoop(Timer.java:555)[:1.7.0_45]
        at java.util.TimerThread.run(Timer.java:505)[:1.7.0_45]
```

After this point, similar errors continue every few seconds until I kill jube.

**Comment by pimlottc** [comment]
Here's the complete startup log:

https://gist.github.com/pimlottc/04a9e7aad5babf04c67f

**Comment by jstrachan** [comment]
BTW I think this is fixed now that jube supports v1beta1 and v1beta2 URLs

**Comment by jstrachan** [comment]
am gonna close for now - let us know if its not fixed and we can reopen
